#! /bin/bash
#SBATCH --job-name=mmcp24-full-md-20
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=72
#SBATCH --partition=small # dev
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --output=output_full-md-20_%j.log
### some additional information (you can delete those lines)
module load mpi
CONFIG="config_full-md-20.xml"

cd /project/MaMiCo/mmcp24-hpcasia-2024/configurations/part1/full-md-domain-sizes
srun <REDACTED>/ls1-mardyn/build/src/MarDyn $CONFIG
